import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import FAQ from "../components/FAQ";
import Footer from "../components/Footer";
import Gallery from "../components/Gallery";
import Hero from "../components/Hero";
import Nav from "../components/Nav";
import Roadmap from "../components/Roadmap";
import Section from "../components/Section";
import Section1 from "../components/Section1";
import Section2 from "../components/Section2";
import Team from "../components/Team";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full  bg-[#171835]">
        <Nav />
        <Hero />
        <About />
        <Gallery />
        <Roadmap />
        <Team />
        {/* <Section1 /> */}
        <Section2 />
        <FAQ />
        <Section />
        <Footer />
      </main>
    </div>
  );
}
